name: Fetch Daily Prices

on:
  schedule:
    - cron: "10 16 * * 1-5"   # 16:10 UTC ≈ 18:10 Stockholm (sommar), ~17:10 (vinter)
  workflow_dispatch:

jobs:
  fetch:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    env:
      PYTHONUNBUFFERED: "1"

    steps:
      - name: Check out repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: pip install --upgrade "yfinance>=0.2.40" "pandas>=2.0.0" requests

      - name: DEBUG – show files
        run: |
          ls -la
          ls -la scripts
          sed -n '1,60p' scripts/fetch_prices.py
          sed -n '1,20p' holdings/watchlist.csv

      - name: Run fetch script
        run: python scripts/fetch_prices.py

      - name: Show output
        run: |
          echo "Contents of data/daily:"
          ls -la data/daily
          echo "Tail of latest file:"
          tail -n +1 data/daily/prices_raw_*.csv | head -n 50

      - name: Commit CSV
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add data/daily/*.csv
          git commit -m "Daily prices" || echo "No changes"
          git push
